### ISSUE TITLE
吃惊

### ISSUE THREAD

**Issue by levy9527** [hustcc/KeyHelper#1]
发现一个既写代码又打Dota的女生.
 的确, 当年才是最好的打Dota的时机, 但我却觉得,Dota毁了大学生活, 让人变宅

**Comment by hustcc** [comment]
哪里看出来我的女生的，好无奈( ˉ ⌓ ˉ ๑)﻿﻿

**Comment by levy9527** [comment]
哈哈, 没办法, 你就像漆黑夜里的萤火虫, 想让人不发现都难
